// Código generado automáticamente. No editar.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Estudiante":return img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.................f...f........
..........f.fffffefff.........
...........feeeeeeeef.........
..........ffeeeeeeeeef........
..........feeeeeeeeeef........
..........feedddeeeeeef.......
..........feedddddddff........
..........fddddcdddcf.........
..........fddddcdddcf.........
...........fddddddddf.........
............fddddddf..........
...........f6fffffff..........
..........f66666666ff.........
..........fdff66666fdf........
..........ffff66666fff........
.............fbbbbbf..........
.............fbf.fbf..........
.............ff..ff...........
..............................
..............................
..............................
..............................
..............................
`;
            case "image2":
            case "Estudiante0":return img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.................f...f........
..........f.fffffefff.........
...........feeeeeeeef.........
..........ffeeeeeeeeef........
..........feeeeeeeeeef........
..........feedddeeeeeef.......
..........feedddddddff........
..........fddddcdddcf.........
..........fddddcdddcf.........
...........fddddddddf.........
............fddddddf..........
...........f6fffffff..........
..........f66666666ff.........
..........fdff66666fdf........
..........ffff66666fff........
.............fbbbbbf..........
.............fbf.fbf..........
.............ff..ff...........
..............................
..............................
..............................
..............................
..............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Código generado automáticamente. No editar.
